//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Туристическое_агенство
{
    using System;
    using System.Collections.Generic;
    
    public partial class Туры
    {
        public int ИД_тура { get; set; }
        public string НазваниеТура { get; set; }
        public string Страна { get; set; }
        public int КоличествоБилетов { get; set; }
        public decimal Цена { get; set; }
        public bool Актуальность { get; set; }
        public string ТипыТуров { get; set; }
    }
}
